apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: edgenetwork-operator
spec:
  generateSelector: true
  parentResource:
    apiVersion: network.edgefarm.io/v1alpha1
    resource: edgenetworks
  childResources:
    - apiVersion: v1
      resource: configmaps
      updateStrategy:
        method: Recreate
    - apiVersion: apps.openyurt.io/v1alpha1
      resource: yurtappdaemons
      updateStrategy:
        method: Recreate
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: Recreate
  hooks:
    sync:
      webhook:
        url: http://edgenetwork-operator.metacontroller/sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgenetwork-operator
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgenetwork-operator
  template:
    metadata:
      labels:
        app: edgenetwork-operator
    spec:
      containers:
        - name: controller
          image: ghcr.io/edgefarm/edgenetwork-operator/edgenetwork-operator:2.0.0
          imagePullPolicy: IfNotPresent
          command: ["/controller"]
          args: ["--log-level", "info"]
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: edgenetwork-operator
  namespace: metacontroller
spec:
  selector:
    app: edgenetwork-operator
  ports:
    - port: 80
      targetPort: 8080
