apiVersion: network.edgefarm.io/v1alpha1
kind: EdgeNetwork
metadata:
  name: mynetwork
  namespace: myconfig
spec:
  network: mynetwork
  subNetwork: mysubnet
  limits:
    fileStorage: 100M
    inMemoryStorage: 100M
  connectionSecretRefs:
    sysAccountUserSecretRef:
      name: mynetwork-sys
    systemUserSecretRef:
      name: mynetwork-system
