apiVersion: network.edgefarm.io/v1alpha1
kind: EdgeNetwork
metadata:
  name: edge-network
  labels:
    foo: bar
spec:
  nodeSelector:
    foo: bar
  network: mynetwork
  connectionSecretRef:
    name: mynetwork
  address: nats.nats
  limits:
    fileStorage: 10G
    inMemoryStorage: 1G
