name: Release

on:
  workflow_run:
    workflows: ["Lint Commit Messages"]
    branches:
      - main
      - beta
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  on-success:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run Tests
        run: |
          make test

      - name: Build the artifacts
        run: |
          make build

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          #!/bin/bash
          set -e
          npm install @semantic-release/exec @semantic-release/git -D
          # the ... || true is to prevent the script from failing caused by a bug in semantic-release regarding 
          # rate limit changes on github. See https://github.com/semantic-release/github/pull/487
          npx -c semantic-release || true
